---
version: 2.6.1
slug: mariadb
name: MariaDB with bugfixes
description: A SQL database server
url: https://github.com/home-assistant/addons/tree/master/mariadb
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
backup_post: "redirfd -wn 1 /proc/1/fd/1 fdmove -c 2 1 \
  s6-rc -v 2 -d change mariadb-lock"
backup_pre: "redirfd -wn 1 /proc/1/fd/1 fdmove -c 2 1 \
  s6-rc -v 2 -u change mariadb-lock"
image: ghcr.io/lmagyar/{arch}-addon-mariadb
init: false
options:
  databases:
    - homeassistant
  logins:
    - password: null
      username: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
ports:
  3306/tcp: null
schema:
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
          CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
          INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
services:
  - mysql:provide
startup: system
timeout: 20
